// This file has been autogenerated from a class added in the UI designer.

using System;

using UIKit;
using Foundation;
using WormHoleSharp;

namespace SampleApp
{
	public partial class ViewController : UIViewController
	{
		Wormhole wormHole;
		public ViewController (IntPtr handle) : base (handle)
		{
			wormHole = new Wormhole ("group.com.clancey.wormhole", "messageDir");
			wormHole.ListenForMessage<string> ("watchButton", (message) => {
				ButtonLabel.Text = message;
			});

			wormHole.PassMessage ("watchButton",1);

		}
		public override void LoadView ()
		{
			base.LoadView ();

			ButtonLabel.Text = wormHole.MessageWithIdentifier<string> ("watchButton");
		}

		partial void SegmentValueChanged (NSObject sender)
		{
			var control = sender as UISegmentedControl;
			wormHole.PassMessage (ButtonMessage.MessageType, new ButtonMessage{ Id =  (int)control.SelectedSegment + 1 });
		}
		[Serializable]
		class ButtonMessage{
			public const string MessageType = "buttonMessage";
			public int Id {get;set;}
		}
	}
}
